# fly.toml app configuration file generated for datapoints-earth on 2023-05-07T21:22:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datapoints-earth"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
